sudo: false
language: java
jdk:
    - oraclejdk8
install: ./gradlew assemble
script: ./gradlew unitTest
cache:
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/gradle-2.4-all/
