sudo: false
language: java
jdk:
    - oraclejdk8
install: ./gradlew -q assemble
script: ./gradlew -q test
cache:
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/dists/gradle-2.4-all/
